[package]
name = "naner"
description = "Portable terminal environment launcher for Windows"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
naner-core.workspace = true
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
